---

language: node_js

node_js:
  - stable

script:
  - make lint
  - make test-coverage

env:
  global:
    - secure: "gVLsXkaxH/B9lDaHAC/wees3Fgy2ct26sNpV2deuLZ3zOOzU3N+PxavlbbjcEAGgX1/nO6Q4UAxCIR6ylftkKCONAqjGHLeIufznN1x69mOXj+4DirS49NpVZEhcV6uHNIqF5bctBJBj4iV+KyysR6D5VEWQ1IxmwU8Tn4sy4tUDdv7QaDmOl9KXAY8sw0FNS9RFxs4Twycke4Vcwz6YTnqUk04Idya0WpNBPIX1WlcHtLhk7JZSBfpeq73ga5/sqWVdd3/hEYq2+5yroQvsE1A0WVEnRWvs6dwQGJNpKVUstl0yzLk33FvRwGpL7pEsNj/3Ep5W/ofH8K7qrb9bi70mhPOBg9wKZCZOA2u4M6Twv8b6vTp0U/gLfE4JGwCJEu+cCD7j+cLLoGS4A3yjIvoUv1o0R6mzayujD1jqGtxNcgpbry7wRd6kMk4hScms+AGaj9/F4+PX5joGhEDB2tKR4e1dJqX5tLj5J/Mm9P4zmJomcAn3X97YQnGADys8VnBfeYERK2DTVCE9zf2W2kuVDCvpYH5b910kvtiJLg4qUMZS217cYLmrcl61wVf36AXUVClUyl8EJgBenQD85bikxVQEnLcXw0vAkUCVacI0DSffh+y5hk7g0rdYSSIMqqSeeXfa/mEsZD+0mYc0t77n3cFVXZx0PR8K3ydmP+U="

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
